/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppStudySessionRouteImport } from './routes/app.study-session'
import { Route as AppStudyPlanRouteImport } from './routes/app.study-plan'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppSearchRouteImport } from './routes/app.search'
import { Route as AppQuizzesRouteImport } from './routes/app.quizzes'
import { Route as AppProgressRouteImport } from './routes/app.progress'
import { Route as AppProgramRouteImport } from './routes/app.program'
import { Route as AppPresentationsRouteImport } from './routes/app.presentations'
import { Route as AppNotesRouteImport } from './routes/app.notes'
import { Route as AppMaterialsRouteImport } from './routes/app.materials'
import { Route as AppLectureMediaRouteImport } from './routes/app.lecture-media'
import { Route as AppImportSyllabusRouteImport } from './routes/app.import-syllabus'
import { Route as AppFlashcardsRouteImport } from './routes/app.flashcards'
import { Route as AppExamEngineRouteImport } from './routes/app.exam-engine'
import { Route as AppDataRouteImport } from './routes/app.data'
import { Route as AppDashboardRouteImport } from './routes/app.dashboard'
import { Route as AppCoursesRouteImport } from './routes/app.courses'
import { Route as AppCalendarRouteImport } from './routes/app.calendar'
import { Route as AppAssignmentsRouteImport } from './routes/app.assignments'
import { Route as AppQuizzesQuizIdRouteImport } from './routes/app.quizzes_.$quizId'
import { Route as AppQuizQualityQuizIdRouteImport } from './routes/app.quiz-quality_.$quizId'
import { Route as AppPresentationsOutlineIdRouteImport } from './routes/app.presentations_.$outlineId'
import { Route as AppNotesNoteIdRouteImport } from './routes/app.notes.$noteId'
import { Route as AppMaterialsMaterialIdRouteImport } from './routes/app.materials_.$materialId'
import { Route as AppCoursesCourseIdRouteImport } from './routes/app.courses_.$courseId'
import { Route as ApiAiTranslateTextRouteImport } from './routes/api/ai/translate-text'
import { Route as ApiAiTranscriptionStatusRouteImport } from './routes/api/ai/transcription-status'
import { Route as ApiAiTranscribeLongMediaRouteImport } from './routes/api/ai/transcribe-long-media'
import { Route as ApiAiStatusRouteImport } from './routes/api/ai/status'
import { Route as ApiAiSimplifyTextRouteImport } from './routes/api/ai/simplify-text'
import { Route as ApiAiReviewOpenAnswerRouteImport } from './routes/api/ai/review-open-answer'
import { Route as ApiAiParseSyllabusRouteImport } from './routes/api/ai/parse-syllabus'
import { Route as ApiAiOcrImageRouteImport } from './routes/api/ai/ocr-image'
import { Route as ApiAiGenerateTopicExplanationRouteImport } from './routes/api/ai/generate-topic-explanation'
import { Route as ApiAiGenerateStudyPackRouteImport } from './routes/api/ai/generate-study-pack'
import { Route as ApiAiGenerateQuizRouteImport } from './routes/api/ai/generate-quiz'
import { Route as ApiAiGeneratePresentationOutlineRouteImport } from './routes/api/ai/generate-presentation-outline'
import { Route as ApiAiGenerateNoteRouteImport } from './routes/api/ai/generate-note'
import { Route as ApiAiGenerateFlashcardsRouteImport } from './routes/api/ai/generate-flashcards'
import { Route as ApiAiGenerateAssignmentBreakdownRouteImport } from './routes/api/ai/generate-assignment-breakdown'
import { Route as ApiAiExtractConceptsRouteImport } from './routes/api/ai/extract-concepts'

const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppStudySessionRoute = AppStudySessionRouteImport.update({
  id: '/study-session',
  path: '/study-session',
  getParentRoute: () => AppRoute,
} as any)
const AppStudyPlanRoute = AppStudyPlanRouteImport.update({
  id: '/study-plan',
  path: '/study-plan',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppSearchRoute = AppSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AppRoute,
} as any)
const AppQuizzesRoute = AppQuizzesRouteImport.update({
  id: '/quizzes',
  path: '/quizzes',
  getParentRoute: () => AppRoute,
} as any)
const AppProgressRoute = AppProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => AppRoute,
} as any)
const AppProgramRoute = AppProgramRouteImport.update({
  id: '/program',
  path: '/program',
  getParentRoute: () => AppRoute,
} as any)
const AppPresentationsRoute = AppPresentationsRouteImport.update({
  id: '/presentations',
  path: '/presentations',
  getParentRoute: () => AppRoute,
} as any)
const AppNotesRoute = AppNotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => AppRoute,
} as any)
const AppMaterialsRoute = AppMaterialsRouteImport.update({
  id: '/materials',
  path: '/materials',
  getParentRoute: () => AppRoute,
} as any)
const AppLectureMediaRoute = AppLectureMediaRouteImport.update({
  id: '/lecture-media',
  path: '/lecture-media',
  getParentRoute: () => AppRoute,
} as any)
const AppImportSyllabusRoute = AppImportSyllabusRouteImport.update({
  id: '/import-syllabus',
  path: '/import-syllabus',
  getParentRoute: () => AppRoute,
} as any)
const AppFlashcardsRoute = AppFlashcardsRouteImport.update({
  id: '/flashcards',
  path: '/flashcards',
  getParentRoute: () => AppRoute,
} as any)
const AppExamEngineRoute = AppExamEngineRouteImport.update({
  id: '/exam-engine',
  path: '/exam-engine',
  getParentRoute: () => AppRoute,
} as any)
const AppDataRoute = AppDataRouteImport.update({
  id: '/data',
  path: '/data',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCoursesRoute = AppCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => AppRoute,
} as any)
const AppCalendarRoute = AppCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AppRoute,
} as any)
const AppAssignmentsRoute = AppAssignmentsRouteImport.update({
  id: '/assignments',
  path: '/assignments',
  getParentRoute: () => AppRoute,
} as any)
const AppQuizzesQuizIdRoute = AppQuizzesQuizIdRouteImport.update({
  id: '/quizzes_/$quizId',
  path: '/quizzes/$quizId',
  getParentRoute: () => AppRoute,
} as any)
const AppQuizQualityQuizIdRoute = AppQuizQualityQuizIdRouteImport.update({
  id: '/quiz-quality_/$quizId',
  path: '/quiz-quality/$quizId',
  getParentRoute: () => AppRoute,
} as any)
const AppPresentationsOutlineIdRoute =
  AppPresentationsOutlineIdRouteImport.update({
    id: '/presentations_/$outlineId',
    path: '/presentations/$outlineId',
    getParentRoute: () => AppRoute,
  } as any)
const AppNotesNoteIdRoute = AppNotesNoteIdRouteImport.update({
  id: '/$noteId',
  path: '/$noteId',
  getParentRoute: () => AppNotesRoute,
} as any)
const AppMaterialsMaterialIdRoute = AppMaterialsMaterialIdRouteImport.update({
  id: '/materials_/$materialId',
  path: '/materials/$materialId',
  getParentRoute: () => AppRoute,
} as any)
const AppCoursesCourseIdRoute = AppCoursesCourseIdRouteImport.update({
  id: '/courses_/$courseId',
  path: '/courses/$courseId',
  getParentRoute: () => AppRoute,
} as any)
const ApiAiTranslateTextRoute = ApiAiTranslateTextRouteImport.update({
  id: '/api/ai/translate-text',
  path: '/api/ai/translate-text',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiTranscriptionStatusRoute =
  ApiAiTranscriptionStatusRouteImport.update({
    id: '/api/ai/transcription-status',
    path: '/api/ai/transcription-status',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAiTranscribeLongMediaRoute =
  ApiAiTranscribeLongMediaRouteImport.update({
    id: '/api/ai/transcribe-long-media',
    path: '/api/ai/transcribe-long-media',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAiStatusRoute = ApiAiStatusRouteImport.update({
  id: '/api/ai/status',
  path: '/api/ai/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiSimplifyTextRoute = ApiAiSimplifyTextRouteImport.update({
  id: '/api/ai/simplify-text',
  path: '/api/ai/simplify-text',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiReviewOpenAnswerRoute = ApiAiReviewOpenAnswerRouteImport.update({
  id: '/api/ai/review-open-answer',
  path: '/api/ai/review-open-answer',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiParseSyllabusRoute = ApiAiParseSyllabusRouteImport.update({
  id: '/api/ai/parse-syllabus',
  path: '/api/ai/parse-syllabus',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiOcrImageRoute = ApiAiOcrImageRouteImport.update({
  id: '/api/ai/ocr-image',
  path: '/api/ai/ocr-image',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiGenerateTopicExplanationRoute =
  ApiAiGenerateTopicExplanationRouteImport.update({
    id: '/api/ai/generate-topic-explanation',
    path: '/api/ai/generate-topic-explanation',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAiGenerateStudyPackRoute = ApiAiGenerateStudyPackRouteImport.update({
  id: '/api/ai/generate-study-pack',
  path: '/api/ai/generate-study-pack',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiGenerateQuizRoute = ApiAiGenerateQuizRouteImport.update({
  id: '/api/ai/generate-quiz',
  path: '/api/ai/generate-quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiGeneratePresentationOutlineRoute =
  ApiAiGeneratePresentationOutlineRouteImport.update({
    id: '/api/ai/generate-presentation-outline',
    path: '/api/ai/generate-presentation-outline',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAiGenerateNoteRoute = ApiAiGenerateNoteRouteImport.update({
  id: '/api/ai/generate-note',
  path: '/api/ai/generate-note',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiGenerateFlashcardsRoute = ApiAiGenerateFlashcardsRouteImport.update({
  id: '/api/ai/generate-flashcards',
  path: '/api/ai/generate-flashcards',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiGenerateAssignmentBreakdownRoute =
  ApiAiGenerateAssignmentBreakdownRouteImport.update({
    id: '/api/ai/generate-assignment-breakdown',
    path: '/api/ai/generate-assignment-breakdown',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAiExtractConceptsRoute = ApiAiExtractConceptsRouteImport.update({
  id: '/api/ai/extract-concepts',
  path: '/api/ai/extract-concepts',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/assignments': typeof AppAssignmentsRoute
  '/app/calendar': typeof AppCalendarRoute
  '/app/courses': typeof AppCoursesRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/data': typeof AppDataRoute
  '/app/exam-engine': typeof AppExamEngineRoute
  '/app/flashcards': typeof AppFlashcardsRoute
  '/app/import-syllabus': typeof AppImportSyllabusRoute
  '/app/lecture-media': typeof AppLectureMediaRoute
  '/app/materials': typeof AppMaterialsRoute
  '/app/notes': typeof AppNotesRouteWithChildren
  '/app/presentations': typeof AppPresentationsRoute
  '/app/program': typeof AppProgramRoute
  '/app/progress': typeof AppProgressRoute
  '/app/quizzes': typeof AppQuizzesRoute
  '/app/search': typeof AppSearchRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/study-plan': typeof AppStudyPlanRoute
  '/app/study-session': typeof AppStudySessionRoute
  '/app/': typeof AppIndexRoute
  '/api/ai/extract-concepts': typeof ApiAiExtractConceptsRoute
  '/api/ai/generate-assignment-breakdown': typeof ApiAiGenerateAssignmentBreakdownRoute
  '/api/ai/generate-flashcards': typeof ApiAiGenerateFlashcardsRoute
  '/api/ai/generate-note': typeof ApiAiGenerateNoteRoute
  '/api/ai/generate-presentation-outline': typeof ApiAiGeneratePresentationOutlineRoute
  '/api/ai/generate-quiz': typeof ApiAiGenerateQuizRoute
  '/api/ai/generate-study-pack': typeof ApiAiGenerateStudyPackRoute
  '/api/ai/generate-topic-explanation': typeof ApiAiGenerateTopicExplanationRoute
  '/api/ai/ocr-image': typeof ApiAiOcrImageRoute
  '/api/ai/parse-syllabus': typeof ApiAiParseSyllabusRoute
  '/api/ai/review-open-answer': typeof ApiAiReviewOpenAnswerRoute
  '/api/ai/simplify-text': typeof ApiAiSimplifyTextRoute
  '/api/ai/status': typeof ApiAiStatusRoute
  '/api/ai/transcribe-long-media': typeof ApiAiTranscribeLongMediaRoute
  '/api/ai/transcription-status': typeof ApiAiTranscriptionStatusRoute
  '/api/ai/translate-text': typeof ApiAiTranslateTextRoute
  '/app/courses/$courseId': typeof AppCoursesCourseIdRoute
  '/app/materials/$materialId': typeof AppMaterialsMaterialIdRoute
  '/app/notes/$noteId': typeof AppNotesNoteIdRoute
  '/app/presentations/$outlineId': typeof AppPresentationsOutlineIdRoute
  '/app/quiz-quality/$quizId': typeof AppQuizQualityQuizIdRoute
  '/app/quizzes/$quizId': typeof AppQuizzesQuizIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app/assignments': typeof AppAssignmentsRoute
  '/app/calendar': typeof AppCalendarRoute
  '/app/courses': typeof AppCoursesRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/data': typeof AppDataRoute
  '/app/exam-engine': typeof AppExamEngineRoute
  '/app/flashcards': typeof AppFlashcardsRoute
  '/app/import-syllabus': typeof AppImportSyllabusRoute
  '/app/lecture-media': typeof AppLectureMediaRoute
  '/app/materials': typeof AppMaterialsRoute
  '/app/notes': typeof AppNotesRouteWithChildren
  '/app/presentations': typeof AppPresentationsRoute
  '/app/program': typeof AppProgramRoute
  '/app/progress': typeof AppProgressRoute
  '/app/quizzes': typeof AppQuizzesRoute
  '/app/search': typeof AppSearchRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/study-plan': typeof AppStudyPlanRoute
  '/app/study-session': typeof AppStudySessionRoute
  '/app': typeof AppIndexRoute
  '/api/ai/extract-concepts': typeof ApiAiExtractConceptsRoute
  '/api/ai/generate-assignment-breakdown': typeof ApiAiGenerateAssignmentBreakdownRoute
  '/api/ai/generate-flashcards': typeof ApiAiGenerateFlashcardsRoute
  '/api/ai/generate-note': typeof ApiAiGenerateNoteRoute
  '/api/ai/generate-presentation-outline': typeof ApiAiGeneratePresentationOutlineRoute
  '/api/ai/generate-quiz': typeof ApiAiGenerateQuizRoute
  '/api/ai/generate-study-pack': typeof ApiAiGenerateStudyPackRoute
  '/api/ai/generate-topic-explanation': typeof ApiAiGenerateTopicExplanationRoute
  '/api/ai/ocr-image': typeof ApiAiOcrImageRoute
  '/api/ai/parse-syllabus': typeof ApiAiParseSyllabusRoute
  '/api/ai/review-open-answer': typeof ApiAiReviewOpenAnswerRoute
  '/api/ai/simplify-text': typeof ApiAiSimplifyTextRoute
  '/api/ai/status': typeof ApiAiStatusRoute
  '/api/ai/transcribe-long-media': typeof ApiAiTranscribeLongMediaRoute
  '/api/ai/transcription-status': typeof ApiAiTranscriptionStatusRoute
  '/api/ai/translate-text': typeof ApiAiTranslateTextRoute
  '/app/courses/$courseId': typeof AppCoursesCourseIdRoute
  '/app/materials/$materialId': typeof AppMaterialsMaterialIdRoute
  '/app/notes/$noteId': typeof AppNotesNoteIdRoute
  '/app/presentations/$outlineId': typeof AppPresentationsOutlineIdRoute
  '/app/quiz-quality/$quizId': typeof AppQuizQualityQuizIdRoute
  '/app/quizzes/$quizId': typeof AppQuizzesQuizIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/assignments': typeof AppAssignmentsRoute
  '/app/calendar': typeof AppCalendarRoute
  '/app/courses': typeof AppCoursesRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/data': typeof AppDataRoute
  '/app/exam-engine': typeof AppExamEngineRoute
  '/app/flashcards': typeof AppFlashcardsRoute
  '/app/import-syllabus': typeof AppImportSyllabusRoute
  '/app/lecture-media': typeof AppLectureMediaRoute
  '/app/materials': typeof AppMaterialsRoute
  '/app/notes': typeof AppNotesRouteWithChildren
  '/app/presentations': typeof AppPresentationsRoute
  '/app/program': typeof AppProgramRoute
  '/app/progress': typeof AppProgressRoute
  '/app/quizzes': typeof AppQuizzesRoute
  '/app/search': typeof AppSearchRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/study-plan': typeof AppStudyPlanRoute
  '/app/study-session': typeof AppStudySessionRoute
  '/app/': typeof AppIndexRoute
  '/api/ai/extract-concepts': typeof ApiAiExtractConceptsRoute
  '/api/ai/generate-assignment-breakdown': typeof ApiAiGenerateAssignmentBreakdownRoute
  '/api/ai/generate-flashcards': typeof ApiAiGenerateFlashcardsRoute
  '/api/ai/generate-note': typeof ApiAiGenerateNoteRoute
  '/api/ai/generate-presentation-outline': typeof ApiAiGeneratePresentationOutlineRoute
  '/api/ai/generate-quiz': typeof ApiAiGenerateQuizRoute
  '/api/ai/generate-study-pack': typeof ApiAiGenerateStudyPackRoute
  '/api/ai/generate-topic-explanation': typeof ApiAiGenerateTopicExplanationRoute
  '/api/ai/ocr-image': typeof ApiAiOcrImageRoute
  '/api/ai/parse-syllabus': typeof ApiAiParseSyllabusRoute
  '/api/ai/review-open-answer': typeof ApiAiReviewOpenAnswerRoute
  '/api/ai/simplify-text': typeof ApiAiSimplifyTextRoute
  '/api/ai/status': typeof ApiAiStatusRoute
  '/api/ai/transcribe-long-media': typeof ApiAiTranscribeLongMediaRoute
  '/api/ai/transcription-status': typeof ApiAiTranscriptionStatusRoute
  '/api/ai/translate-text': typeof ApiAiTranslateTextRoute
  '/app/courses_/$courseId': typeof AppCoursesCourseIdRoute
  '/app/materials_/$materialId': typeof AppMaterialsMaterialIdRoute
  '/app/notes/$noteId': typeof AppNotesNoteIdRoute
  '/app/presentations_/$outlineId': typeof AppPresentationsOutlineIdRoute
  '/app/quiz-quality_/$quizId': typeof AppQuizQualityQuizIdRoute
  '/app/quizzes_/$quizId': typeof AppQuizzesQuizIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/app/assignments'
    | '/app/calendar'
    | '/app/courses'
    | '/app/dashboard'
    | '/app/data'
    | '/app/exam-engine'
    | '/app/flashcards'
    | '/app/import-syllabus'
    | '/app/lecture-media'
    | '/app/materials'
    | '/app/notes'
    | '/app/presentations'
    | '/app/program'
    | '/app/progress'
    | '/app/quizzes'
    | '/app/search'
    | '/app/settings'
    | '/app/study-plan'
    | '/app/study-session'
    | '/app/'
    | '/api/ai/extract-concepts'
    | '/api/ai/generate-assignment-breakdown'
    | '/api/ai/generate-flashcards'
    | '/api/ai/generate-note'
    | '/api/ai/generate-presentation-outline'
    | '/api/ai/generate-quiz'
    | '/api/ai/generate-study-pack'
    | '/api/ai/generate-topic-explanation'
    | '/api/ai/ocr-image'
    | '/api/ai/parse-syllabus'
    | '/api/ai/review-open-answer'
    | '/api/ai/simplify-text'
    | '/api/ai/status'
    | '/api/ai/transcribe-long-media'
    | '/api/ai/transcription-status'
    | '/api/ai/translate-text'
    | '/app/courses/$courseId'
    | '/app/materials/$materialId'
    | '/app/notes/$noteId'
    | '/app/presentations/$outlineId'
    | '/app/quiz-quality/$quizId'
    | '/app/quizzes/$quizId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app/assignments'
    | '/app/calendar'
    | '/app/courses'
    | '/app/dashboard'
    | '/app/data'
    | '/app/exam-engine'
    | '/app/flashcards'
    | '/app/import-syllabus'
    | '/app/lecture-media'
    | '/app/materials'
    | '/app/notes'
    | '/app/presentations'
    | '/app/program'
    | '/app/progress'
    | '/app/quizzes'
    | '/app/search'
    | '/app/settings'
    | '/app/study-plan'
    | '/app/study-session'
    | '/app'
    | '/api/ai/extract-concepts'
    | '/api/ai/generate-assignment-breakdown'
    | '/api/ai/generate-flashcards'
    | '/api/ai/generate-note'
    | '/api/ai/generate-presentation-outline'
    | '/api/ai/generate-quiz'
    | '/api/ai/generate-study-pack'
    | '/api/ai/generate-topic-explanation'
    | '/api/ai/ocr-image'
    | '/api/ai/parse-syllabus'
    | '/api/ai/review-open-answer'
    | '/api/ai/simplify-text'
    | '/api/ai/status'
    | '/api/ai/transcribe-long-media'
    | '/api/ai/transcription-status'
    | '/api/ai/translate-text'
    | '/app/courses/$courseId'
    | '/app/materials/$materialId'
    | '/app/notes/$noteId'
    | '/app/presentations/$outlineId'
    | '/app/quiz-quality/$quizId'
    | '/app/quizzes/$quizId'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/app/assignments'
    | '/app/calendar'
    | '/app/courses'
    | '/app/dashboard'
    | '/app/data'
    | '/app/exam-engine'
    | '/app/flashcards'
    | '/app/import-syllabus'
    | '/app/lecture-media'
    | '/app/materials'
    | '/app/notes'
    | '/app/presentations'
    | '/app/program'
    | '/app/progress'
    | '/app/quizzes'
    | '/app/search'
    | '/app/settings'
    | '/app/study-plan'
    | '/app/study-session'
    | '/app/'
    | '/api/ai/extract-concepts'
    | '/api/ai/generate-assignment-breakdown'
    | '/api/ai/generate-flashcards'
    | '/api/ai/generate-note'
    | '/api/ai/generate-presentation-outline'
    | '/api/ai/generate-quiz'
    | '/api/ai/generate-study-pack'
    | '/api/ai/generate-topic-explanation'
    | '/api/ai/ocr-image'
    | '/api/ai/parse-syllabus'
    | '/api/ai/review-open-answer'
    | '/api/ai/simplify-text'
    | '/api/ai/status'
    | '/api/ai/transcribe-long-media'
    | '/api/ai/transcription-status'
    | '/api/ai/translate-text'
    | '/app/courses_/$courseId'
    | '/app/materials_/$materialId'
    | '/app/notes/$noteId'
    | '/app/presentations_/$outlineId'
    | '/app/quiz-quality_/$quizId'
    | '/app/quizzes_/$quizId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ApiAiExtractConceptsRoute: typeof ApiAiExtractConceptsRoute
  ApiAiGenerateAssignmentBreakdownRoute: typeof ApiAiGenerateAssignmentBreakdownRoute
  ApiAiGenerateFlashcardsRoute: typeof ApiAiGenerateFlashcardsRoute
  ApiAiGenerateNoteRoute: typeof ApiAiGenerateNoteRoute
  ApiAiGeneratePresentationOutlineRoute: typeof ApiAiGeneratePresentationOutlineRoute
  ApiAiGenerateQuizRoute: typeof ApiAiGenerateQuizRoute
  ApiAiGenerateStudyPackRoute: typeof ApiAiGenerateStudyPackRoute
  ApiAiGenerateTopicExplanationRoute: typeof ApiAiGenerateTopicExplanationRoute
  ApiAiOcrImageRoute: typeof ApiAiOcrImageRoute
  ApiAiParseSyllabusRoute: typeof ApiAiParseSyllabusRoute
  ApiAiReviewOpenAnswerRoute: typeof ApiAiReviewOpenAnswerRoute
  ApiAiSimplifyTextRoute: typeof ApiAiSimplifyTextRoute
  ApiAiStatusRoute: typeof ApiAiStatusRoute
  ApiAiTranscribeLongMediaRoute: typeof ApiAiTranscribeLongMediaRoute
  ApiAiTranscriptionStatusRoute: typeof ApiAiTranscriptionStatusRoute
  ApiAiTranslateTextRoute: typeof ApiAiTranslateTextRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/study-session': {
      id: '/app/study-session'
      path: '/study-session'
      fullPath: '/app/study-session'
      preLoaderRoute: typeof AppStudySessionRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/study-plan': {
      id: '/app/study-plan'
      path: '/study-plan'
      fullPath: '/app/study-plan'
      preLoaderRoute: typeof AppStudyPlanRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/search': {
      id: '/app/search'
      path: '/search'
      fullPath: '/app/search'
      preLoaderRoute: typeof AppSearchRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/quizzes': {
      id: '/app/quizzes'
      path: '/quizzes'
      fullPath: '/app/quizzes'
      preLoaderRoute: typeof AppQuizzesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/progress': {
      id: '/app/progress'
      path: '/progress'
      fullPath: '/app/progress'
      preLoaderRoute: typeof AppProgressRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/program': {
      id: '/app/program'
      path: '/program'
      fullPath: '/app/program'
      preLoaderRoute: typeof AppProgramRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/presentations': {
      id: '/app/presentations'
      path: '/presentations'
      fullPath: '/app/presentations'
      preLoaderRoute: typeof AppPresentationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/notes': {
      id: '/app/notes'
      path: '/notes'
      fullPath: '/app/notes'
      preLoaderRoute: typeof AppNotesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/materials': {
      id: '/app/materials'
      path: '/materials'
      fullPath: '/app/materials'
      preLoaderRoute: typeof AppMaterialsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/lecture-media': {
      id: '/app/lecture-media'
      path: '/lecture-media'
      fullPath: '/app/lecture-media'
      preLoaderRoute: typeof AppLectureMediaRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/import-syllabus': {
      id: '/app/import-syllabus'
      path: '/import-syllabus'
      fullPath: '/app/import-syllabus'
      preLoaderRoute: typeof AppImportSyllabusRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/flashcards': {
      id: '/app/flashcards'
      path: '/flashcards'
      fullPath: '/app/flashcards'
      preLoaderRoute: typeof AppFlashcardsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/exam-engine': {
      id: '/app/exam-engine'
      path: '/exam-engine'
      fullPath: '/app/exam-engine'
      preLoaderRoute: typeof AppExamEngineRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/data': {
      id: '/app/data'
      path: '/data'
      fullPath: '/app/data'
      preLoaderRoute: typeof AppDataRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/courses': {
      id: '/app/courses'
      path: '/courses'
      fullPath: '/app/courses'
      preLoaderRoute: typeof AppCoursesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/calendar': {
      id: '/app/calendar'
      path: '/calendar'
      fullPath: '/app/calendar'
      preLoaderRoute: typeof AppCalendarRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/assignments': {
      id: '/app/assignments'
      path: '/assignments'
      fullPath: '/app/assignments'
      preLoaderRoute: typeof AppAssignmentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/quizzes_/$quizId': {
      id: '/app/quizzes_/$quizId'
      path: '/quizzes/$quizId'
      fullPath: '/app/quizzes/$quizId'
      preLoaderRoute: typeof AppQuizzesQuizIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/quiz-quality_/$quizId': {
      id: '/app/quiz-quality_/$quizId'
      path: '/quiz-quality/$quizId'
      fullPath: '/app/quiz-quality/$quizId'
      preLoaderRoute: typeof AppQuizQualityQuizIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/presentations_/$outlineId': {
      id: '/app/presentations_/$outlineId'
      path: '/presentations/$outlineId'
      fullPath: '/app/presentations/$outlineId'
      preLoaderRoute: typeof AppPresentationsOutlineIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/notes/$noteId': {
      id: '/app/notes/$noteId'
      path: '/$noteId'
      fullPath: '/app/notes/$noteId'
      preLoaderRoute: typeof AppNotesNoteIdRouteImport
      parentRoute: typeof AppNotesRoute
    }
    '/app/materials_/$materialId': {
      id: '/app/materials_/$materialId'
      path: '/materials/$materialId'
      fullPath: '/app/materials/$materialId'
      preLoaderRoute: typeof AppMaterialsMaterialIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/courses_/$courseId': {
      id: '/app/courses_/$courseId'
      path: '/courses/$courseId'
      fullPath: '/app/courses/$courseId'
      preLoaderRoute: typeof AppCoursesCourseIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/ai/translate-text': {
      id: '/api/ai/translate-text'
      path: '/api/ai/translate-text'
      fullPath: '/api/ai/translate-text'
      preLoaderRoute: typeof ApiAiTranslateTextRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/transcription-status': {
      id: '/api/ai/transcription-status'
      path: '/api/ai/transcription-status'
      fullPath: '/api/ai/transcription-status'
      preLoaderRoute: typeof ApiAiTranscriptionStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/transcribe-long-media': {
      id: '/api/ai/transcribe-long-media'
      path: '/api/ai/transcribe-long-media'
      fullPath: '/api/ai/transcribe-long-media'
      preLoaderRoute: typeof ApiAiTranscribeLongMediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/status': {
      id: '/api/ai/status'
      path: '/api/ai/status'
      fullPath: '/api/ai/status'
      preLoaderRoute: typeof ApiAiStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/simplify-text': {
      id: '/api/ai/simplify-text'
      path: '/api/ai/simplify-text'
      fullPath: '/api/ai/simplify-text'
      preLoaderRoute: typeof ApiAiSimplifyTextRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/review-open-answer': {
      id: '/api/ai/review-open-answer'
      path: '/api/ai/review-open-answer'
      fullPath: '/api/ai/review-open-answer'
      preLoaderRoute: typeof ApiAiReviewOpenAnswerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/parse-syllabus': {
      id: '/api/ai/parse-syllabus'
      path: '/api/ai/parse-syllabus'
      fullPath: '/api/ai/parse-syllabus'
      preLoaderRoute: typeof ApiAiParseSyllabusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/ocr-image': {
      id: '/api/ai/ocr-image'
      path: '/api/ai/ocr-image'
      fullPath: '/api/ai/ocr-image'
      preLoaderRoute: typeof ApiAiOcrImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/generate-topic-explanation': {
      id: '/api/ai/generate-topic-explanation'
      path: '/api/ai/generate-topic-explanation'
      fullPath: '/api/ai/generate-topic-explanation'
      preLoaderRoute: typeof ApiAiGenerateTopicExplanationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/generate-study-pack': {
      id: '/api/ai/generate-study-pack'
      path: '/api/ai/generate-study-pack'
      fullPath: '/api/ai/generate-study-pack'
      preLoaderRoute: typeof ApiAiGenerateStudyPackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/generate-quiz': {
      id: '/api/ai/generate-quiz'
      path: '/api/ai/generate-quiz'
      fullPath: '/api/ai/generate-quiz'
      preLoaderRoute: typeof ApiAiGenerateQuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/generate-presentation-outline': {
      id: '/api/ai/generate-presentation-outline'
      path: '/api/ai/generate-presentation-outline'
      fullPath: '/api/ai/generate-presentation-outline'
      preLoaderRoute: typeof ApiAiGeneratePresentationOutlineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/generate-note': {
      id: '/api/ai/generate-note'
      path: '/api/ai/generate-note'
      fullPath: '/api/ai/generate-note'
      preLoaderRoute: typeof ApiAiGenerateNoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/generate-flashcards': {
      id: '/api/ai/generate-flashcards'
      path: '/api/ai/generate-flashcards'
      fullPath: '/api/ai/generate-flashcards'
      preLoaderRoute: typeof ApiAiGenerateFlashcardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/generate-assignment-breakdown': {
      id: '/api/ai/generate-assignment-breakdown'
      path: '/api/ai/generate-assignment-breakdown'
      fullPath: '/api/ai/generate-assignment-breakdown'
      preLoaderRoute: typeof ApiAiGenerateAssignmentBreakdownRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/extract-concepts': {
      id: '/api/ai/extract-concepts'
      path: '/api/ai/extract-concepts'
      fullPath: '/api/ai/extract-concepts'
      preLoaderRoute: typeof ApiAiExtractConceptsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppNotesRouteChildren {
  AppNotesNoteIdRoute: typeof AppNotesNoteIdRoute
}

const AppNotesRouteChildren: AppNotesRouteChildren = {
  AppNotesNoteIdRoute: AppNotesNoteIdRoute,
}

const AppNotesRouteWithChildren = AppNotesRoute._addFileChildren(
  AppNotesRouteChildren,
)

interface AppRouteChildren {
  AppAssignmentsRoute: typeof AppAssignmentsRoute
  AppCalendarRoute: typeof AppCalendarRoute
  AppCoursesRoute: typeof AppCoursesRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppDataRoute: typeof AppDataRoute
  AppExamEngineRoute: typeof AppExamEngineRoute
  AppFlashcardsRoute: typeof AppFlashcardsRoute
  AppImportSyllabusRoute: typeof AppImportSyllabusRoute
  AppLectureMediaRoute: typeof AppLectureMediaRoute
  AppMaterialsRoute: typeof AppMaterialsRoute
  AppNotesRoute: typeof AppNotesRouteWithChildren
  AppPresentationsRoute: typeof AppPresentationsRoute
  AppProgramRoute: typeof AppProgramRoute
  AppProgressRoute: typeof AppProgressRoute
  AppQuizzesRoute: typeof AppQuizzesRoute
  AppSearchRoute: typeof AppSearchRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppStudyPlanRoute: typeof AppStudyPlanRoute
  AppStudySessionRoute: typeof AppStudySessionRoute
  AppIndexRoute: typeof AppIndexRoute
  AppCoursesCourseIdRoute: typeof AppCoursesCourseIdRoute
  AppMaterialsMaterialIdRoute: typeof AppMaterialsMaterialIdRoute
  AppPresentationsOutlineIdRoute: typeof AppPresentationsOutlineIdRoute
  AppQuizQualityQuizIdRoute: typeof AppQuizQualityQuizIdRoute
  AppQuizzesQuizIdRoute: typeof AppQuizzesQuizIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAssignmentsRoute: AppAssignmentsRoute,
  AppCalendarRoute: AppCalendarRoute,
  AppCoursesRoute: AppCoursesRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppDataRoute: AppDataRoute,
  AppExamEngineRoute: AppExamEngineRoute,
  AppFlashcardsRoute: AppFlashcardsRoute,
  AppImportSyllabusRoute: AppImportSyllabusRoute,
  AppLectureMediaRoute: AppLectureMediaRoute,
  AppMaterialsRoute: AppMaterialsRoute,
  AppNotesRoute: AppNotesRouteWithChildren,
  AppPresentationsRoute: AppPresentationsRoute,
  AppProgramRoute: AppProgramRoute,
  AppProgressRoute: AppProgressRoute,
  AppQuizzesRoute: AppQuizzesRoute,
  AppSearchRoute: AppSearchRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppStudyPlanRoute: AppStudyPlanRoute,
  AppStudySessionRoute: AppStudySessionRoute,
  AppIndexRoute: AppIndexRoute,
  AppCoursesCourseIdRoute: AppCoursesCourseIdRoute,
  AppMaterialsMaterialIdRoute: AppMaterialsMaterialIdRoute,
  AppPresentationsOutlineIdRoute: AppPresentationsOutlineIdRoute,
  AppQuizQualityQuizIdRoute: AppQuizQualityQuizIdRoute,
  AppQuizzesQuizIdRoute: AppQuizzesQuizIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ApiAiExtractConceptsRoute: ApiAiExtractConceptsRoute,
  ApiAiGenerateAssignmentBreakdownRoute: ApiAiGenerateAssignmentBreakdownRoute,
  ApiAiGenerateFlashcardsRoute: ApiAiGenerateFlashcardsRoute,
  ApiAiGenerateNoteRoute: ApiAiGenerateNoteRoute,
  ApiAiGeneratePresentationOutlineRoute: ApiAiGeneratePresentationOutlineRoute,
  ApiAiGenerateQuizRoute: ApiAiGenerateQuizRoute,
  ApiAiGenerateStudyPackRoute: ApiAiGenerateStudyPackRoute,
  ApiAiGenerateTopicExplanationRoute: ApiAiGenerateTopicExplanationRoute,
  ApiAiOcrImageRoute: ApiAiOcrImageRoute,
  ApiAiParseSyllabusRoute: ApiAiParseSyllabusRoute,
  ApiAiReviewOpenAnswerRoute: ApiAiReviewOpenAnswerRoute,
  ApiAiSimplifyTextRoute: ApiAiSimplifyTextRoute,
  ApiAiStatusRoute: ApiAiStatusRoute,
  ApiAiTranscribeLongMediaRoute: ApiAiTranscribeLongMediaRoute,
  ApiAiTranscriptionStatusRoute: ApiAiTranscriptionStatusRoute,
  ApiAiTranslateTextRoute: ApiAiTranslateTextRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
